name: Docker Image Build and Deploy

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}
        
    - uses: actions/checkout@v2
   
    - name: Build parent image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{github.repository}}:latest
